config/routes.rb
BootOverflow::Application.routes.draw do

  root :to => 'questions#index'
  resources :users , :except => [:index]
  match '/profile' => 'users#show'

  resources :questions do
    resources :answers, :except => [:index, :show] do
      resources :upvotes, :only => [:create]
      resources :downvotes, :only => [:create]
    end
    resources :upvotes, :only => [:create]
    resources :downvotes, :only => [:create]
  end
  
  get "/user/login" => 'users#login'
  post "/user/login" => 'users#authenticate'
  get "/user/logout" => 'users#logout'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :title, :content, :user_id, :question_id, :up_votes, :down_votes

  belongs_to :question
  belongs_to :user

  make_voteable

  validates :title, :presence => true
  validates :content, :presence => true
  validates :user_id, :presence => true
  validates :question_id, :presence => true

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :title, :content, :user_id, :up_votes, :down_votes
  make_voteable

  belongs_to :user
  has_many :answers



  validates :title, :presence => true
  validates :content, :presence => true
  validates :user_id, :presence => true

end

app/models/user.rb
class User < ActiveRecord::Base

  make_voter

  validates :name, :presence => true 
  validates :username, :uniqueness => true
  validates :email, :presence => true, :uniqueness => true
  validates :password_digest, :presence => true


  attr_accessible :name, :username, :email, :password, :password_confirmation

  has_secure_password
  has_many :questions
  has_many :answers

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	def create
		@question = Question.find(params[:question_id])
		@answer = Answer.create(title: params[:answer][:title], content: params[:answer][:content], user_id: current_user.id, question_id: params[:question_id])
		redirect_to @question
	end

	def new
		@question = Question.find(params[:question_id])
	end

	def edit
		@answer = Answer.find(params[:id])
		if current_user.id == @answer.user_id
			# render template
		else
			flash[:notice] = "You cannot edit another user's answer"
		end
	end

	def update
	end

	def destroy
		@answer = Answer.find(params[:id])
		if current_user.id == @answer.user_id
			@answer.destroy
		else
			flash[:notice] = "You cannot delete another user's answer"
		end
	end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include Authentication

  helper_method :current_user

end

app/controllers/downvotes_controller.rb
class DownvotesController < ApplicationController
 
 def create
   @question = Question.find(params[:question_id])
  if params.include?(:answer_id)
    @answer = Answer.find(params[:answer_id])
    current_user.down_vote!(@answer)
  else
    current_user.down_vote!(@question)
  end
    redirect_to @question
 end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	def index
		@questions = Question.all
	end

	def create
		p params
		@question = Question.create(title: params[:question][:title], content: params[:question][:content], 
			user_id: current_user.id)
		redirect_to questions_path(@question)
	end

	def new
		@question = Question.new
	end

	def edit
		@question = Question.find(params[:id])
		if current_user.id == @question.user_id
			# render template
		else
			flash[:notice] = "You cannot edit another user's question"
		end
	end

	def show
		@question = Question.find(params[:id])
		@answer= Answer.new
	end

	def update
		@question = Question.find(params[:id])
	end

	def destroy
		@question = Question.find(params[:id])
		if current_user.id == @question.user_id
			@question.destroy
		else
			flash[:notice] = "You cannot delete another user's question"
		end
	end 

end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
 
 def create
    @question = Question.find(params[:question_id])
  if params.include?(:answer_id)
    @answer = Answer.find(params[:answer_id])
    current_user.up_vote!(@answer)
  else
    current_user.up_vote!(@question)
  end
    redirect_to @question
 end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
  def new
    @user = User.new
  end

	def create
    @user = User.new(params[:user])
    if @user.save
      session[:id] = @user.id
      redirect_to @user
    else
      render :new
    end
	end



	def edit
	end

	def show
	end

	def update
		current_user.update_attributes(params[:user])
	end

	def destroy
		current_user.destroy
		redirect_to '/'
	end 
  
  def login

  end

  def authenticate
  	authenticate_user(params) 
  end

  def logout
  	session.clear
  	redirect_to '/'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/edit.html.haml
new.html.haml

app/views/answers/new.html.haml
.container 
  %h1 Write a new Answer!
  - form_for @answer do |f|
    = f.label "Title:"
    = f.text_field :title
    = f.label "Add Answer:"
    = f.text_field :content
    = f.submit

app/views/layouts/application.html.haml
%html
  %head
    %title BootOverflow
    = stylesheet_link_tag   "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render :partial => "questions/nav"
    = yield

app/views/questions/_nav.html.haml
%nav
  
  %ul
    %li 
      = link_to "Home", root_path
    - if current_user
      %li
        = link_to "Profile", profile_path
      %li
        = link_to "Ask Question", new_question_path
      %li
        = link_to "Logout", user_logout_path
    - else
      %li
        = link_to "Login", user_login_path
      %li
        = link_to "Sign Up", new_user_path

app/views/questions/create.html.erb
create.html.erb

app/views/questions/edit.html.haml
.container 
  %h1 Edit your question!

app/views/questions/index.html.haml
.container 
  %h1 Welcome New Boots!

  - @questions.each_with_index do |question, index| 
    %ul
      %li
        = question.title
        = question.content
        = question.votes
        = link_to "&#8593;".html_safe, question_upvotes_path(question), :method => :post, :id => 'upvote' + (index + 1).to_s, :remote => true 
        = link_to "&#8595;".html_safe, question_downvotes_path(question), :method => :post, :id => 'downvote' + (index + 1).to_s, :remote => true 

app/views/questions/new.html.haml
.container 
  %h1 Ask a new Question!
  = form_for @question do |f|
    = f.label "Title:"
    = f.text_field :title
    = f.label "Content:"
    = f.text_area :content
    = f.submit
   

app/views/questions/question.html.haml
.container Here is your single question

app/views/questions/show.html.haml
.container 
  %p
    = @question.votes
    = @question.title
    = @question.content
    = link_to "&#9650;".html_safe, question_upvotes_path(@question), :method => :post, :remote => true 
    = link_to "&#9660;".html_safe, question_downvotes_path(@question), :method => :post, :remote => true 
    %br
    %br


  %p
    = form_for [@question, @answer] do |f|
      = f.label "Title:"
      = f.text_field :title
      = f.label "Add Answer:"
      = f.text_field :content
      = f.submit

  %p
    - @question.answers.each do |answer|
      = answer.votes
      = answer.title
      = answer.content
      = link_to "&#9650;".html_safe, question_answer_upvotes_path(@question, answer), :method => :post 
      = link_to "&#9660;".html_safe, question_answer_downvotes_path(@question, answer), :method => :post 
      

app/views/shared/_form_errors.html.haml
.errors
  - object.errors.full_messages.each do |error|
    = error

app/views/users/edit.html.haml
.container 
  %h1 Edit your User!

app/views/users/index.html.haml
.container 
  %h1 Show all Users!

app/views/users/login.html.haml
.container
  %h1 Please Log in!
  = form_tag user_login_path do
    #email
      = label_tag :email
      = text_field_tag :email
    #password
      = label_tag :password
      = password_field_tag :password
      = submit_tag "Log In"

app/views/users/new.html.haml
.container 
  %h1 Please Sign up!
  = form_for(@user) do |f|
    = render 'shared/form_errors', :object => @user if @user.errors.present?
    %p
      = f.label :name
    %p
      = f.text_field :name
    %p
      = f.label :username
    %p
      = f.text_field :username
    %p
      = f.label :email
    %p 
      = f.text_field :email
    %p
      = f.label :password
    %p 
      = f.text_field :password
    %p
      = f.label :password_confirmation
    %p 
      = f.text_field :password_confirmation
      = f.submit "Sign Up"

app/views/users/show.html.haml
.container 
  %h1 User Profile!
 